# Generated by Django 5.2.4 on 2026-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfn', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Октрыт'), ('closed', 'Закрыт')], default='open', max_length=6, verbose_name='Статус проекта'),
        ),
    ]
